In [1]:
import torch
from torch import nn
m = nn.Conv2d(174, 80, (3,1), stride=(2,1)) 
input = torch.randn(5, 174, 60, 54)
input = m(input)

In [2]:
input.shape

torch.Size([5, 80, 29, 54])

In [3]:
m = nn.Conv2d(80, 30, (3,1), stride=(2,1)) 
input = m(input)

In [4]:
input.shape

torch.Size([5, 30, 14, 54])

In [5]:
m = nn.Conv2d(30, 10, (3,1), stride=(2,1)) 
input = m(input)

In [6]:
input.shape

torch.Size([5, 10, 6, 54])

In [7]:
xx=nn.Flatten()
flattened = xx(input)
flattened.shape

torch.Size([5, 3240])

In [9]:
from model import Dirichlet
cc=Dirichlet()

TypeError: __init__() missing 2 required positional arguments: 'inputs' and 'model'

In [21]:
import pandas as pd
from price_generators import ComputationalSignalManager
signal_path='./signals.csv'
signals=pd.read_csv(signal_path)
signal_stream=ComputationalSignalManager("6/22/2015","2/28/2019",signals,54,83)

In [22]:
import numpy as np

fff=signal_stream.forward()
s=np.sum(fff)
date=None
while s==0:
    new_signals=signal_stream.forward()
    date=signal_stream.current_date
    s=np.sum(new_signals)
print(new_signals)



[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 ...

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]]


In [23]:
print(np.sum(new_signals))
print(date)

38.649998
2015-11-21 00:00:00


In [24]:
fff=signal_stream.forward()

In [27]:
print(fff.sum())
print(s)

38.649998
38.649998


In [33]:
while s<39:
    new_signals=signal_stream.forward()
    date=signal_stream.current_date
    s=np.sum(new_signals)
print(new_signals)

[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 ...

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]]


In [36]:
new_signals.shape

(83, 2, 54)

In [38]:
for i in range(83):
    for j in range(2):
        for k in range(54):
            if new_signals[i,j,k]!=0:
                print(i)
                print(j)
                print(k)
                print(new_signals[i,j,k])

53
0
30
43.71
53
1
30
-5.06
56
0
41
17.68
56
1
41
-10.89


IndexError: index 83 is out of bounds for axis 0 with size 83

In [40]:
if (-1<-2):
    print("sssssssssss")